Repository Avanade/Liquid-Application-Framework, pull requests merged in 2019-12, with the labels that each got.

#117 fix: sample builds sucessful with release flag
  samples/Liquid.Sample.CarRegistry/Controllers/CarController.cs
Labels: bug

#109 refactor: remove the method ValidateInterfaces from WorkBench
  src/Liquid.Base/WorkBench.cs
Labels: bug, enhancement

#131 refactor: remove duplicate ICriticHandler property from LightDomain
  src/Liquid.Base/Interfaces/Domain/ILightDomain.cs
  src/Liquid.Domain/Base/Domain/LightDomain.cs
Labels: enhancement
